integration: Print cache hit number if cache fails.
- Now when the test fails due to cache not returning the same thing
  whether it is warm or not, we see which cache hit was responsible.

- Example failing test output:

--- FAIL: TestGetRunningDeploymentSet_testCluster (0.98s)
        Error Trace:    integration_test.go:81
        Error:          Not equal: "91495f1b1630084e301241100ecf2e775f6b672c" (expected)
                                != "" (actual)
        Messages:       on cache hit 2